theme: minima
title: Github Page
author: jemimabooker
email: ****
description: > # this means to ignore newlines until "baseurl:"
  This is my github page

# social links
github_username:  jemimabooker

show_excerpts: true # set to false to remove excerpts on the homepage
